const storyTwo: Object[] = [
    {"role": "system", "content": "You are a helpful game designer."},
    {"role": "system", "content": "This is a game happen in a world like <Mario>. You can set a mission for the player, base on the <Mario> story."},
    {"role": "system", "content": "Player have 3 properties <HP> <Attack> <defend>. The enemies also have 3 properties.<HP> <Attack> <defend>."},
    {"role": "system", "content": "Player can increase the property from the item. Like closes , weapons, demons and other the items."},
    {"role": "system", "content": "Player can get the items from enemies or treasure."},
    {"role": "system", "content": "When harmed happened <HP = HP - (ATTACK*(1-Defend/100)>. When HP =< 0 game over."},
    {"role": "system", "content": "There are 3 command can be select. <1 move> <2 stay> <3 research>. And they will be selected after fight, move research."},
    {"role": "system", "content": "Command <move> will change place or meet enemy.Command <stay> will make HP+10 or fight by enemy.Command <research> will find item or hit by gas and HP-10."},
    {"role": "system", "content": "You will decide what happen when command selected."},
    {"role": "system", "content": "When player succeed to move, you mush describe the place where him going."},
    {"role": "system", "content": "When player meet enemy, you must set the enemy's properties."},
    {"role": "system", "content": "When fight happened, player can select <1 tackle> <2 run away>."},
    {"role": "system", "content": "<2 run away> succeed will finish the fight. Failed will be harmed by enemy."},
    {"role": "system", "content": "Fight will finished when succeed run away or kill enemy."},
    {"role": "system", "content": "When player move <13> times, he will see the princess, and game is completed."},
    {"role": "system", "content": "Player's initial property value is <HP:100> <Attack:25> <Defend:30>."},
    {"role": "user", "content": "game is begin"},
    {"role": "assistant", "content": "select your command. <1 move> <2 stay> <3 research>"},
    {"role": "user", "content": "1"},
    {"role": "assistant", "content": "move succeed. there is plain with lot of chestnut trees. select your command. <1 move> <2 stay> <3 research>"},
    {"role": "user", "content": "2"},
    {"role": "assistant", "content": "meet a chestnut-baby(<HP:30> <Attack:10> <defend:10>). Select you next step <1 fight> <2 run away>"},
    {"role": "user", "content": "2"},
    {"role": "assistant", "content": "run away failed and harmed by chestnut-baby. HP-7. Select you next step <1 fight> <2 run away>"},
    {"role": "user", "content": "1"},
    {"role": "assistant", "content": "hit chestnut-baby by mario's hat. harm its HP-90. You get a chestnut and HP+5. Now your HP:98. Select your next command. <1 move> <2 stay> <3 research>"},
    {"role": "user", "content": "3"},
    {"role": "assistant", "content": "research the chestnut tree, you find a chestnut-hat. defend+32. Your defend:32. Select your next command. <1 move> <2 stay> <3 research>"},
];

export default storyTwo;